version: "3.8"

networks:
  dashboards:

services:
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "${NGINX_PORT:-80}:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: [ dashboards ]


  eth-p2p-dashboard:
    image: "eth-dashboard:latest"
    build:
      context: ./eth-dashboard
      dockerfile: Dockerfile
    volumes:
      - ./eth-dashboard/nginx:/etc/nginx/conf.d
      - ./eth-dashboard/templates/:/dashboard/templates/
    restart: unless-stopped
    networks: [ dashboards ]
    ports:
      - "${ETH_DASHBOARD_PORT:-5070}:5085"
    environment:
      - WEB_BASE_ENDP=${WEB_BASE_ENDP}

  plotly-generator:
    restart: unless-stopped
    build:
      context: ./plotly_gen
      dockerfile: Dockerfile
    volumes:
      - ./eth-dashboard/templates/:/plotly_gen/generated
      - ./plotly_gen/logs:/plotly_gen/logs
      - ./plotly_gen/generated_old:/plotly_gen/generated_old
      - ./.env:/plotly_gen/.env
    network_mode: "host"
