version: "3.9"

networks:
  dashboards:

services:
  xatu-dashboard:
    image: "eth-dashboard:latest"
    build:
      context: ./xatu-dashboard
      dockerfile: Dockerfile
    volumes:
      - ./xatu-dashboard/nginx:/etc/nginx/conf.d
      - ./xatu-dashboard/pages/:/dashboard/pages/
    restart: unless-stopped
    networks: [ dashboards ]
    ports:
      - "${ETH_DASHBOARD_PORT:-5070}:5085"
    environment:
      - WEB_BASE_ENDP=${WEB_BASE_ENDP}

  plotly-generator:
    restart: unless-stopped
    build:
      context: ./plotly_gen
      dockerfile: Dockerfile
    volumes:
      - ./xatu-dashboard/pages/:/plotly_gen/generated
      - ./plotly_gen/logs:/plotly_gen/logs
      - ./plotly_gen/generated_old:/plotly_gen/generated_old
      - ./.env:/plotly_gen/.env
